language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.8.5
# Install our package "." http://stackoverflow.com/a/27091478
install:
  - pip install flake8
  - pip install .
before_script:
  - flake8
script:
  - cd testproject
  - ./manage.py test
