language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.8.5
install:
  - pip install flake8 Django==$DJANGO_VERSION six
before_script:
  - flake8
script:
  - cd testproject
  - ./manage.py test
