language: python
python:
# - "2.7"
# - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.10.6
# Install our package "." http://stackoverflow.com/a/27091478
install:
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  - flake8
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - coverage run --source xvalidate ./manage.py test
# Report to coveralls
after_success:
  - coveralls
